### PR TITLE
Bug fix: == to =

### PR DESCRIPTION
**Pull request by cameron-erdogan**

### CODE REVIEW

**Comment by armadillu** [comment]
wow this is bad, thx!

**Comment by cameron-erdogan** [comment]
All good! I found it the hard way, but was only flailing for about an hour.

**Comment by armadillu** [comment]
Sorry to hear about your pain. I never really get assets without checksums, too many risks involved... So this part of the code never got tested.

**Comment by cameron-erdogan** [comment]
Checksums mostly have to do with reading from a database correct? The backend we use seems to handle that without us having to worry about it. I haven't actually dealt with a backend that exposed checksums.

**Pull request merged**
